{
    'name': 'dck_blancoamor',
    'version': '13.0.0.0',
    'category': 'Tools',
    'summary': "Proyecto ba con geo",
    'author': 'Ing. Gabriela Rivero',
    'depends': [
        'base',
    ],
    'data': [
    ],
    'installable': True,
    'application': False,
    'external_dependencies': {'python':['twilio']},
    'limit_request': '8196',
    'limit_memory_soft': '640000000',
    'limit_memory_hard': '760000000',
    'limit_time_cpu': '60',
    'limit_time_real': '120',

    # manifest version, if omitted it is backward compatible
    'env-ver': '2',

    # if Enterprise it installs in a different directory than community
    'odoo-license': 'CE',

    # port where odoo starts serving pages
    'port': '8016',
    'longpolling_port': '8078',

    # list of url repos to install in the form 'repo-url directory'
    'git-repos': [
        'https://github.com/filoquin/cl-blancoamor.git',
        'git@code.gestionblancoamor.com:odoo-13/ba_sales.git -b13.0 ba-ba-sales',
        'git@code.gestionblancoamor.com:odoo-13/ba_base.git -b13.0 ba-ba-base',
        'git@code.gestionblancoamor.com:odoo-13/ba_delivery_zone.git -b13.0 ba-ba-stock',
        'git@code.gestionblancoamor.com:odoo-13/ba_product.git -b13.0 ba-ba-product',
        'git@code.gestionblancoamor.com:odoo-13/ba_purchase.git -b13.0 ba-ba-purchase',
        'git@code.gestionblancoamor.com:odoo-13/ba_website.git -b13.0 ba-ba-website',
        'git@code.gestionblancoamor.com:odoo-13/ba_campus.git -b13.0.git ba-ba-campus',
        'git@code.gestionblancoamor.com:filoquin/website_themes.git ba -b13.0 varios-website_themes',
        'git@code.gestionblancoamor.com:filoquin/ux.git -b13.0 varios-ba-ux',
        'git@code.gestionblancoamor.com:odoo-13/ks_dashboard_ninja.git ba -b13.0 varios-ks_dashboard_ninja',
        'git@code.gestionblancoamor.com:odoo-13/ba_hr -b13.0 ba-ba_hr',
        'https://github.com/ingadhoc/account-analytic.git -b 13.0 adhoc-account-analytic',
        'https://github.com/ingadhoc/account-invoicing.git -b 13.0 adhoc-account-invoicing',
        'https://github.com/ingadhoc/argentina-sale.git -b 13.0 adhoc-argentina-sale',
        'https://github.com/ingadhoc/multi-company.git -b 13.0 adhoc-multi-company',
        'https://github.com/ingadhoc/odoo-argentina.git -b 13.0 adhoc-odoo-argentina',
        'https://github.com/ingadhoc/product.git -b 13.0 adhoc-product',
        'https://github.com/ingadhoc/purchase.git -b 13.0 adhoc-purchase',
        'https://github.com/ingadhoc/stock.git -b 13.0 adhoc-stock',
        'https://github.com/ingadhoc/account-financial-tools.git -b 13.0 account-adhoc-financial-tools',
        'https://github.com/ingadhoc/account-payment.git -b 13.0 adhoc-account-payment',
        'https://github.com/ingadhoc/miscellaneous.git -b 13.0 adhoc-miscellaneous',
        'https://github.com/ingadhoc/multi-store.git -b 13.0 adhoc-multi-store',
        'https://github.com/ingadhoc/project.git -b 13.0 adhoc-project',
        'https://github.com/ingadhoc/sale.git -b 13.0 adhoc-sale ',
        'https://github.com/ingadhoc/website.git -b 13.0 adhoc-website',
        'https://github.com/hormigaG/odoo-argentina-ce.git -b 13.0_BA adhoc-odoo-argentina-ce',
        'https://github.com/OCA/account-analytic.git -b13.0 oca-account-analytic',
        'https://github.com/OCA/crm.git -b13.0 oca-crm',
        'https://github.com/OCA/hr-expense.git -b13.0 oca-hr-expense',
        'https://github.com/OCA/management-system.git -b13.0 oca-management-system',
        'https://github.com/OCA/project.git -b13.0 oca-project',
        'https://github.com/OCA/sale-financial.git -b13.0 oca-sale-financial',
        'https://github.com/OCA/server-ux.git -b13.0 oca-server-ux',
        'https://github.com/OCA/web.git -b13.0 oca-web',
        'https://github.com/OCA/account-financial-reporting.git -b13.0 oca-account-financial-reporting',
        'https://github.com/OCA/geospatial.git -b13.0 oca-geospatial',
        'https://github.com/OCA/hr-holidays.git -b13.0 oca-hr-holidays',
        'https://github.com/OCA/partner-contact.git -b13.0 oca-partner-contact',
        'https://github.com/OCA/purchase-workflow.git -b13.0 oca-purchase-workflow',
        'https://github.com/OCA/sale-workflow.git -b13.0 oca-sale-workflow',
        'https://github.com/OCA/social.git -b13.0 oca-social',
        'https://github.com/OCA/wms.git -b13.0 oca-wms',
        'https://github.com/OCA/account-financial-tools.git -b13.0 oca-account-financial-tools',
        'https://github.com/OCA/hr.git -b13.0 oca-hr',
        'https://github.com/OCA/knowledge.git -b13.0 oca-knowledge',
        'https://github.com/OCA/product-attribute.git -b13.0 oca-product-attribute',
        'https://github.com/OCA/queue.git -b13.0 oca-queue',
        'https://github.com/OCA/server-brand.git -b13.0 oca-server-brand',
        'https://github.com/OCA/stock-logistics-warehouse.git -b13.0 oca-stock-logistics-warehouse',
        'https://github.com/OCA/brand.git -b13.0 oca-brand',
        'https://github.com/OCA/hr-attendance.git -b13.0 oca-hr-attendance',
        'https://github.com/OCA/maintenance.git -b13.0 oca-maintenance',
        'https://github.com/OCA/product-pack.git -b13.0 oca-product-pack',
        'https://github.com/OCA/reporting-engine.git -b13.0 oca-reporting-engine',
        'https://github.com/OCA/server-tools.git -b13.0 oca-server-tools',
        'https://github.com/OCA/stock-logistics-workflow.git -b13.0 oca-stock-logistics-workflow',
        'https://github.com/OCA/contract.git -b13.0 oca-contract',
        'https://github.com/OCA/bank-statement-import.git -b13.0 oca-bank-statement-import',
        'https://github.com/OCA/server-backend.git -b13.0 oca-server-backend',
        'https://github.com/OCA/account-invoicing/ -b13.0 oca-account-invoicing',
        'https://github.com/OCA/payroll.git -b13.0 oca-payroll',
        'https://github.com/OCA/e-commerce.git -b13.0 oca-e-commerce',
        'https://github.com/OCA/delivery-carrier.git -b13.0 oca-delivery-carrier',

        'git@code.gestionblancoamor.com:odoo-13/blancoamor.git'

    ],
    'docker-images': [
        'odoo regaby/odoo-ce:13.0',
        # 'postgres postgres:10.1-alpine',
        'postgres mdillon/postgis:11-alpine',
        #'nginx nginx'
    ]
    #'base_dir': '/opt/odoo/docker_files/'
}
